# Site settings
encoding: utf-8
title: LightDoc 演示
email: 469379004@qq.com
keywords: lightdoc,jekyll,文档,document,ruby,api
description: LightDoc是一个基于Jekyll开发的文档系统。
baseurl: "/lightdoc/"
url: "https://clyoko.coding.me"
#github_username:  clyoko
exclude:  ["README.md",".git",".idea"]
# Build settings
markdown: kramdown
